sales_analytics:
    outputs:
        dev:
            type: postgres
            host: epsi_dataops-postgres-1
            port: 5432
            user: airflow
            password: airflow
            dbname: airflow_db
            schema: public
            threads: 4
    target: dev
